export interface PowerPollEntry {
  rank: number;
  team: string;
  slug?: string;
  identity: string;
  path: string;
  watch: string;
  logoHint?: string;
  abbreviation?: string;
}

export const POWER_POLL_ENTRIES: PowerPollEntry[] = [
  {
    rank: 1,
    team: 'Purdue',
    slug: 'purdue',
    identity: 'Continuity, elite half-court execution, high assist rate, deliberate pace.',
    path: 'Own the glass, limit live-ball turnovers, schedule has few landmines before league play.',
    watch: 'Top-5 offensive efficiency with FT rate edge.',
    logoHint: 'Purdue Boilermakers',
    abbreviation: 'PUR',
  },
  {
    rank: 2,
    team: 'Houston',
    slug: 'houston',
    identity: 'Top-3 defense again, turnover creation, guards who pressure and finish.',
    path: 'Transition points off steals, late-clock offense improvement.',
    watch: 'Opponent eFG% and TO% both top-10.',
    logoHint: 'Houston Cougars',
    abbreviation: 'HOU',
  },
  {
    rank: 3,
    team: 'Florida',
    slug: 'florida',
    identity: 'Champion’s shot profile carries over: rim + corner 3s, deep rotation.',
    path: 'Defensive rebounding vs power bigs, foul avoidance.',
    watch: 'ORtg stays top-10 without slippage in D-glass.',
    logoHint: 'Florida Gators',
    abbreviation: 'UF',
  },
  {
    rank: 4,
    team: 'UConn',
    slug: 'uconn',
    identity: 'Disciplined defense, set-piece mastery, NBA-size wings.',
    path: 'Early chemistry, bench scoring.',
    watch: 'Half-court PPP vs ranked teams.',
    logoHint: 'Connecticut Huskies',
    abbreviation: 'UCON',
  },
  {
    rank: 5,
    team: "St. John's",
    slug: 'st-johns',
    identity: 'Physicality, switchable 2-4, garden-variety chaos into easy buckets.',
    path: 'Shot selection vs zones, late-game composure.',
    watch: 'FT attempt rate vs Big East heavies.',
    logoHint: "St. John's Red Storm",
    abbreviation: 'SJU',
  },
  {
    rank: 6,
    team: 'Duke',
    slug: 'duke',
    identity: 'Shot-creation at 1/3, rim protection enough to stay aggressive on the perimeter.',
    path: 'Defensive rebounding, reduce midrange drift.',
    watch: '3PA rate without losing paint touches.',
    logoHint: 'Duke Blue Devils',
    abbreviation: 'DUKE',
  },
  {
    rank: 7,
    team: 'Michigan',
    slug: 'michigan',
    identity: 'Balanced, inside-out offense, sturdy defensive shell.',
    path: 'Turnover margin vs pressure teams.',
    watch: 'Post-touch efficiency and kick-out 3s.',
    logoHint: 'Michigan Wolverines',
    abbreviation: 'MICH',
  },
  {
    rank: 8,
    team: 'BYU',
    slug: 'byu',
    identity: 'Spacing, shooting depth, motion into flare actions.',
    path: 'Defensive rebounding travel-proof.',
    watch: '3P rate versus top-25 defenses.',
    logoHint: 'BYU Cougars',
    abbreviation: 'BYU',
  },
  {
    rank: 9,
    team: 'Kentucky',
    slug: 'kentucky',
    identity: 'Pace, athletes everywhere, rim pressure.',
    path: 'Experience curve on defense; keep TOs sub-17%.',
    watch: 'Early pick-and-roll coverage consistency.',
    logoHint: 'Kentucky Wildcats',
    abbreviation: 'UK',
  },
  {
    rank: 10,
    team: 'Texas Tech',
    slug: 'texas-tech',
    identity: 'Connected defense, low-mistake offense.',
    path: 'Free throws created by wings.',
    watch: 'Opponent 3P volume suppression.',
    logoHint: 'Texas Tech Red Raiders',
    abbreviation: 'TTU',
  },
  {
    rank: 11,
    team: 'Louisville',
    slug: 'louisville',
    identity: 'Size, mid-post scoring options, slotted roles.',
    path: 'Perimeter defense vs spread attacks.',
    watch: 'Foul rate of primary bigs.',
    logoHint: 'Louisville Cardinals',
    abbreviation: 'LOU',
  },
  {
    rank: 12,
    team: 'UCLA',
    slug: 'ucla',
    identity: 'Compact defense, controlled pace, surgical sets.',
    path: 'Find reliable secondary creator.',
    watch: 'Assist rate in late-clock possessions.',
    logoHint: 'UCLA Bruins',
    abbreviation: 'UCLA',
  },
  {
    rank: 13,
    team: 'Arizona',
    slug: 'arizona',
    identity: 'Tempo and early offense, stretch-bigs trailing for threes.',
    path: 'Half-court stops; avoid whistle-heavy games.',
    watch: 'Transition PPP vs top-50.',
    logoHint: 'Arizona Wildcats',
    abbreviation: 'ARIZ',
  },
  {
    rank: 14,
    team: 'Arkansas',
    slug: 'arkansas',
    identity: 'Downhill guards, offensive boards, free throws.',
    path: 'Spacing around slashing.',
    watch: 'Lineup 3-point gravity.',
    logoHint: 'Arkansas Razorbacks',
    abbreviation: 'ARK',
  },
  {
    rank: 15,
    team: 'Alabama',
    slug: 'alabama',
    identity: 'Math problem team: rim/3s, massive pace.',
    path: 'Defensive volatility control.',
    watch: 'Opponent rim attempts allowed.',
    logoHint: 'Alabama Crimson Tide',
    abbreviation: 'BAMA',
  },
  {
    rank: 16,
    team: 'Iowa State',
    slug: 'iowa-state',
    identity: 'Turnover factory, disciplined close-outs.',
    path: 'Half-court creation in tight games.',
    watch: 'Live-ball TO rate vs ranked guards.',
    logoHint: 'Iowa State Cyclones',
    abbreviation: 'ISU',
  },
  {
    rank: 17,
    team: 'Illinois',
    slug: 'illinois',
    identity: 'Veteran shot makers, strong defensive rebounding.',
    path: 'Guard the arc better.',
    watch: 'Opp 3P% regression and contest rate.',
    logoHint: 'Illinois Fighting Illini',
    abbreviation: 'ILL',
  },
  {
    rank: 18,
    team: 'Tennessee',
    slug: 'tennessee',
    identity: 'Defense travels; switch, contest, rebound.',
    path: 'Free-throw economy for the offense.',
    watch: 'FT rate generated by guards.',
    logoHint: 'Tennessee Volunteers',
    abbreviation: 'TENN',
  },
  {
    rank: 19,
    team: 'Kansas',
    slug: 'kansas',
    identity: 'Structure, two-way wings, high-IQ sets.',
    path: 'Reliable spacing from 2-3 bench pieces.',
    watch: 'Corner-3 frequency.',
    logoHint: 'Kansas Jayhawks',
    abbreviation: 'KU',
  },
  {
    rank: 20,
    team: 'Auburn',
    slug: 'auburn',
    identity: 'Rim protection and vertical spacing.',
    path: 'Turnover avoidance at pace.',
    watch: 'Block rate without foul spikes.',
    logoHint: 'Auburn Tigers',
    abbreviation: 'AUB',
  },
  {
    rank: 21,
    team: 'Gonzaga',
    slug: 'gonzaga',
    identity: 'Continuity offense, inside-out reads.',
    path: 'Athleticism at the point of attack on D.',
    watch: 'Opponent rim FG%.',
    logoHint: 'Gonzaga Bulldogs',
    abbreviation: 'GONZ',
  },
  {
    rank: 22,
    team: 'Michigan State',
    slug: 'michigan-state',
    identity: 'Defensive spine, rebounding culture, veteran backcourt.',
    path: 'Dependable late-clock creator.',
    watch: 'Mid-range efficiency in clutch time.',
    logoHint: 'Michigan State Spartans',
    abbreviation: 'MSU',
  },
  {
    rank: 23,
    team: 'Creighton',
    slug: 'creighton',
    identity: 'Spacing, ball security, five-man skill.',
    path: 'Bench minutes that hold serve.',
    watch: 'Non-starter net rating.',
    logoHint: 'Creighton Bluejays',
    abbreviation: 'CREI',
  },
  {
    rank: 24,
    team: 'Wisconsin',
    slug: 'wisconsin',
    identity: 'Slowdown, shot quality, defensive positioning.',
    path: 'Maintain low foul rate vs drivers.',
    watch: 'Opponent FT rate in Big Ten play.',
    logoHint: 'Wisconsin Badgers',
    abbreviation: 'WISC',
  },
  {
    rank: 25,
    team: 'North Carolina',
    slug: 'north-carolina',
    identity: 'Tempo toggling, secondary break, defensive glass.',
    path: 'Three-point volume without shot selection tax.',
    watch: '3PA share and turnover rate trend.',
    logoHint: 'North Carolina Tar Heels',
    abbreviation: 'UNC',
  },
];

export const POWER_POLL_CONTEXT: string[] = [
  'AP preseason Top-25 drives the order above. Coaches poll mirrors the same top tier.',
  'National outlets peg similar contenders at the very top; Houston, Purdue, Florida, UConn regularly appear in the first cluster across preseason models and editorials.',
];
