// This file is auto-generated by scripts/build-ncaa-logo-map.mjs
export interface LogoEntry {
  readonly name: string;
  readonly slug: string;
  readonly tokens: readonly string[];
  readonly path: string;
}

export const NCAA_LOGOS: readonly LogoEntry[] = [
  {
    "name": "Air Force Falcons",
    "slug": "air-force-falcons",
    "tokens": [
      "air",
      "force",
      "falcons"
    ],
    "path": "assets/logos/ncaa/Air_Force_Falcons_logo-300x300.png"
  },
  {
    "name": "Akron Zips",
    "slug": "akron-zips",
    "tokens": [
      "akron",
      "zips"
    ],
    "path": "assets/logos/ncaa/Akron_Zips_logo-300x300.png"
  },
  {
    "name": "Alabama Crimson Tide",
    "slug": "alabama-crimson-tide",
    "tokens": [
      "alabama",
      "crimson",
      "tide"
    ],
    "path": "assets/logos/ncaa/Alabama_Crimson_Tide_logo-300x300.png"
  },
  {
    "name": "UAB Blazers",
    "slug": "uab-blazers",
    "tokens": [
      "uab",
      "blazers"
    ],
    "path": "assets/logos/ncaa/Alabama-Birmingham-Blazers-logo-300x300.png"
  },
  {
    "name": "American Athletic Conference",
    "slug": "american-athletic-conference",
    "tokens": [
      "american",
      "athletic",
      "conference"
    ],
    "path": "assets/logos/ncaa/American_Athletic_Conference_logo-300x300.png"
  },
  {
    "name": "Appalachian State Mountaineers",
    "slug": "appalachian-state-mountaineers",
    "tokens": [
      "appalachian",
      "state",
      "mountaineers"
    ],
    "path": "assets/logos/ncaa/Appalachian_State_Mountaineers_logo-300x300.png"
  },
  {
    "name": "Arizona State Sun Devils",
    "slug": "arizona-state-sun-devils",
    "tokens": [
      "arizona",
      "state",
      "sun",
      "devils"
    ],
    "path": "assets/logos/ncaa/Arizona_State_Sun_Devils_logo-300x300.png"
  },
  {
    "name": "Arizona Wildcats",
    "slug": "arizona-wildcats",
    "tokens": [
      "arizona",
      "wildcats"
    ],
    "path": "assets/logos/ncaa/Arizona_Wildcats_logo-300x300.png"
  },
  {
    "name": "Arkansas Razorbacks",
    "slug": "arkansas-razorbacks",
    "tokens": [
      "arkansas",
      "razorbacks"
    ],
    "path": "assets/logos/ncaa/Arkansas_Razorbacks_logo-300x300.png"
  },
  {
    "name": "Arkansas State Red Wolves",
    "slug": "arkansas-state-red-wolves",
    "tokens": [
      "arkansas",
      "state",
      "red",
      "wolves"
    ],
    "path": "assets/logos/ncaa/Arkansas_State_Red_Wolves_logo-300x300.png"
  },
  {
    "name": "Army West Point Black Knights",
    "slug": "army-west-point-black-knights",
    "tokens": [
      "army",
      "west",
      "point",
      "black",
      "knights"
    ],
    "path": "assets/logos/ncaa/Army_West_Point_Black_Knights_logo-300x300.png"
  },
  {
    "name": "ACC",
    "slug": "acc",
    "tokens": [
      "acc"
    ],
    "path": "assets/logos/ncaa/Atlantic_Coast_Conference_ACC_logo-300x300.png"
  },
  {
    "name": "Auburn Tigers",
    "slug": "auburn-tigers",
    "tokens": [
      "auburn",
      "tigers"
    ],
    "path": "assets/logos/ncaa/Auburn_Tigers_logo-300x300.png"
  },
  {
    "name": "Ball State Cardinals",
    "slug": "ball-state-cardinals",
    "tokens": [
      "ball",
      "state",
      "cardinals"
    ],
    "path": "assets/logos/ncaa/Ball_State_Cardinals_logo-300x300.png"
  },
  {
    "name": "Baylor Bears",
    "slug": "baylor-bears",
    "tokens": [
      "baylor",
      "bears"
    ],
    "path": "assets/logos/ncaa/Baylor_Bears_logo-300x300.png"
  },
  {
    "name": "Big 12 Conference",
    "slug": "big-12-conference",
    "tokens": [
      "big",
      "12",
      "conference"
    ],
    "path": "assets/logos/ncaa/Big_12_Conference_logo-300x300.png"
  },
  {
    "name": "Big Ten Conference",
    "slug": "big-ten-conference",
    "tokens": [
      "big",
      "ten",
      "conference"
    ],
    "path": "assets/logos/ncaa/Big_Ten_Conference_logo-300x300.png"
  },
  {
    "name": "Boise State Broncos",
    "slug": "boise-state-broncos",
    "tokens": [
      "boise",
      "state",
      "broncos"
    ],
    "path": "assets/logos/ncaa/Boise_State_Broncos_Logo-300x300.png"
  },
  {
    "name": "Boston College Eagles",
    "slug": "boston-eagles",
    "tokens": [
      "boston",
      "eagles"
    ],
    "path": "assets/logos/ncaa/Boston_College_Eagles_logo-300x300.png"
  },
  {
    "name": "Bowling Green Falcons",
    "slug": "bowling-green-falcons",
    "tokens": [
      "bowling",
      "green",
      "falcons"
    ],
    "path": "assets/logos/ncaa/Bowling_Green_Falcons_logo-300x300.png"
  },
  {
    "name": "Buffalo Bulls",
    "slug": "buffalo-bulls",
    "tokens": [
      "buffalo",
      "bulls"
    ],
    "path": "assets/logos/ncaa/Buffalo_Bulls_logo-300x300.png"
  },
  {
    "name": "BYU Cougars",
    "slug": "byu-cougars",
    "tokens": [
      "byu",
      "cougars"
    ],
    "path": "assets/logos/ncaa/BYU_Cougars_logo-300x300.png"
  },
  {
    "name": "California Golden Bears",
    "slug": "california-golden-bears",
    "tokens": [
      "california",
      "golden",
      "bears"
    ],
    "path": "assets/logos/ncaa/California_Golden_Bears_logo-300x300.png"
  },
  {
    "name": "Central Michigan Chippewas",
    "slug": "central-michigan-chippewas",
    "tokens": [
      "central",
      "michigan",
      "chippewas"
    ],
    "path": "assets/logos/ncaa/Central_Michigan_Chippewas_logo-300x300.png"
  },
  {
    "name": "Charlotte 49ers",
    "slug": "charlotte-49ers",
    "tokens": [
      "charlotte",
      "49ers"
    ],
    "path": "assets/logos/ncaa/Charlotte_49ers_logo-300x300.png"
  },
  {
    "name": "Cincinnati Bearcats",
    "slug": "cincinnati-bearcats",
    "tokens": [
      "cincinnati",
      "bearcats"
    ],
    "path": "assets/logos/ncaa/Cincinnati_Bearcats_logo-300x300.png"
  },
  {
    "name": "Clemson Tigers",
    "slug": "clemson-tigers",
    "tokens": [
      "clemson",
      "tigers"
    ],
    "path": "assets/logos/ncaa/Clemson_Tigers_logo-300x300.png"
  },
  {
    "name": "Coastal Carolina Chanticleers",
    "slug": "coastal-carolina-chanticleers",
    "tokens": [
      "coastal",
      "carolina",
      "chanticleers"
    ],
    "path": "assets/logos/ncaa/Coastal_Carolina_Chanticleers_logo-300x300.png"
  },
  {
    "name": "Colorado Buffaloes",
    "slug": "colorado-buffaloes",
    "tokens": [
      "colorado",
      "buffaloes"
    ],
    "path": "assets/logos/ncaa/Colorado_Buffaloes_logo-300x300.png"
  },
  {
    "name": "Colorado State Rams",
    "slug": "colorado-state-rams",
    "tokens": [
      "colorado",
      "state",
      "rams"
    ],
    "path": "assets/logos/ncaa/Colorado_State_Rams_logo-300x300.png"
  },
  {
    "name": "Conference USA",
    "slug": "conference-usa",
    "tokens": [
      "conference",
      "usa"
    ],
    "path": "assets/logos/ncaa/Conference_USA_logo-300x300.png"
  },
  {
    "name": "Connecticut Huskies",
    "slug": "connecticut-huskies",
    "tokens": [
      "connecticut",
      "huskies"
    ],
    "path": "assets/logos/ncaa/Connecticut_Huskies_logo-300x300.png"
  },
  {
    "name": "Division I FBS Independents",
    "slug": "division-i-fbs-independents",
    "tokens": [
      "division",
      "i",
      "fbs",
      "independents"
    ],
    "path": "assets/logos/ncaa/Division-I-FBS-Independents-logo-300x300.png"
  },
  {
    "name": "Duke Blue Devils",
    "slug": "duke-blue-devils",
    "tokens": [
      "duke",
      "blue",
      "devils"
    ],
    "path": "assets/logos/ncaa/Duke_Blue_Devils_logo-300x300.png"
  },
  {
    "name": "East Carolina Pirates",
    "slug": "east-carolina-pirates",
    "tokens": [
      "east",
      "carolina",
      "pirates"
    ],
    "path": "assets/logos/ncaa/East_Carolina_Pirates_logo-300x300.png"
  },
  {
    "name": "Eastern Michigan Eagles",
    "slug": "eastern-michigan-eagles",
    "tokens": [
      "eastern",
      "michigan",
      "eagles"
    ],
    "path": "assets/logos/ncaa/Eastern_Michigan_Eagles_logo-300x300.png"
  },
  {
    "name": "FIU Panthers",
    "slug": "fiu-panthers",
    "tokens": [
      "fiu",
      "panthers"
    ],
    "path": "assets/logos/ncaa/FIU-Panthers-Logo-300x300.png"
  },
  {
    "name": "Florida Atlantic Owls",
    "slug": "florida-atlantic-owls",
    "tokens": [
      "florida",
      "atlantic",
      "owls"
    ],
    "path": "assets/logos/ncaa/Florida_Atlantic_Owls_logo-300x300.png"
  },
  {
    "name": "Florida Gators",
    "slug": "florida-gators",
    "tokens": [
      "florida",
      "gators"
    ],
    "path": "assets/logos/ncaa/Florida_Gators_logo-300x300.png"
  },
  {
    "name": "Florida State Seminoles",
    "slug": "florida-state-seminoles",
    "tokens": [
      "florida",
      "state",
      "seminoles"
    ],
    "path": "assets/logos/ncaa/Florida_State_Seminoles_logo-300x300.png"
  },
  {
    "name": "Fresno State Bulldogs",
    "slug": "fresno-state-bulldogs",
    "tokens": [
      "fresno",
      "state",
      "bulldogs"
    ],
    "path": "assets/logos/ncaa/Fresno_State_Bulldogs_logo-300x300.png"
  },
  {
    "name": "Georgia Bulldogs",
    "slug": "georgia-bulldogs",
    "tokens": [
      "georgia",
      "bulldogs"
    ],
    "path": "assets/logos/ncaa/Georgia_Bulldogs_logo-300x300.png"
  },
  {
    "name": "Georgia Southern Eagles",
    "slug": "georgia-southern-eagles",
    "tokens": [
      "georgia",
      "southern",
      "eagles"
    ],
    "path": "assets/logos/ncaa/Georgia_Southern_Eagles_logo-300x300.png"
  },
  {
    "name": "Georgia State Panthers",
    "slug": "georgia-state-panthers",
    "tokens": [
      "georgia",
      "state",
      "panthers"
    ],
    "path": "assets/logos/ncaa/Georgia_State_Panthers_logo-300x300.png"
  },
  {
    "name": "Georgia Tech Yellow Jackets",
    "slug": "georgia-tech-yellow-jackets",
    "tokens": [
      "georgia",
      "tech",
      "yellow",
      "jackets"
    ],
    "path": "assets/logos/ncaa/Georgia_Tech_Yellow_Jackets_logo-300x300.png"
  },
  {
    "name": "Hawaii Rainbow Warriors",
    "slug": "hawaii-rainbow-warriors",
    "tokens": [
      "hawaii",
      "rainbow",
      "warriors"
    ],
    "path": "assets/logos/ncaa/Hawaii_Rainbow_Warriors_logo-300x300.png"
  },
  {
    "name": "Houston Cougars",
    "slug": "houston-cougars",
    "tokens": [
      "houston",
      "cougars"
    ],
    "path": "assets/logos/ncaa/Houston_Cougars_logo-300x300.png"
  },
  {
    "name": "Illinois Fighting Illini",
    "slug": "illinois-fighting-illini",
    "tokens": [
      "illinois",
      "fighting",
      "illini"
    ],
    "path": "assets/logos/ncaa/Illinois_Fighting_Illini_logo-300x300.png"
  },
  {
    "name": "Indiana Hoosiers",
    "slug": "indiana-hoosiers",
    "tokens": [
      "indiana",
      "hoosiers"
    ],
    "path": "assets/logos/ncaa/Indiana_Hoosiers_logo-300x300.png"
  },
  {
    "name": "Iowa Hawkeyes",
    "slug": "iowa-hawkeyes",
    "tokens": [
      "iowa",
      "hawkeyes"
    ],
    "path": "assets/logos/ncaa/Iowa_Hawkeyes_logo-300x300.png"
  },
  {
    "name": "Iowa State Cyclones",
    "slug": "iowa-state-cyclones",
    "tokens": [
      "iowa",
      "state",
      "cyclones"
    ],
    "path": "assets/logos/ncaa/Iowa_State_Cyclones_logo-300x300.png"
  },
  {
    "name": "Jacksonville State Gamecocks",
    "slug": "jacksonville-state-gamecocks",
    "tokens": [
      "jacksonville",
      "state",
      "gamecocks"
    ],
    "path": "assets/logos/ncaa/Jacksonville-State-Gamecocks-logo-300x300.png"
  },
  {
    "name": "James Madison Dukes",
    "slug": "james-madison-dukes",
    "tokens": [
      "james",
      "madison",
      "dukes"
    ],
    "path": "assets/logos/ncaa/James_Madison_Dukes_logo-300x300.png"
  },
  {
    "name": "Kansas Jayhawks",
    "slug": "kansas-jayhawks",
    "tokens": [
      "kansas",
      "jayhawks"
    ],
    "path": "assets/logos/ncaa/Kansas_Jayhawks_logo-300x300.png"
  },
  {
    "name": "Kansas State Wildcats",
    "slug": "kansas-state-wildcats",
    "tokens": [
      "kansas",
      "state",
      "wildcats"
    ],
    "path": "assets/logos/ncaa/Kansas_State_Wildcats_logo-300x300.png"
  },
  {
    "name": "Kennesaw State Owls",
    "slug": "kennesaw-state-owls",
    "tokens": [
      "kennesaw",
      "state",
      "owls"
    ],
    "path": "assets/logos/ncaa/Kennesaw-State-Owls-logo-300x300.png"
  },
  {
    "name": "Kent State Golden Flashes",
    "slug": "kent-state-golden-flashes",
    "tokens": [
      "kent",
      "state",
      "golden",
      "flashes"
    ],
    "path": "assets/logos/ncaa/Kent_State_Golden_Flashes-300x300.png"
  },
  {
    "name": "Kentucky Wildcats",
    "slug": "kentucky-wildcats",
    "tokens": [
      "kentucky",
      "wildcats"
    ],
    "path": "assets/logos/ncaa/Kentucky_Wildcats_logo-300x300.png"
  },
  {
    "name": "Liberty Flames",
    "slug": "liberty-flames",
    "tokens": [
      "liberty",
      "flames"
    ],
    "path": "assets/logos/ncaa/Liberty_Flames_logo-300x300.png"
  },
  {
    "name": "Louisiana Tech Bulldogs",
    "slug": "louisiana-tech-bulldogs",
    "tokens": [
      "louisiana",
      "tech",
      "bulldogs"
    ],
    "path": "assets/logos/ncaa/Louisiana_Tech_Bulldogs_logo-300x300.png"
  },
  {
    "name": "Louisiana Ragin Cajuns",
    "slug": "louisiana-ragin-cajuns",
    "tokens": [
      "louisiana",
      "ragin",
      "cajuns"
    ],
    "path": "assets/logos/ncaa/Louisiana-Lafayette_Ragin_Cajuns_logo-300x300.png"
  },
  {
    "name": "ULM Warhawks",
    "slug": "ulm-warhawks",
    "tokens": [
      "ulm",
      "warhawks"
    ],
    "path": "assets/logos/ncaa/Louisiana-Monroe_Warhawks_logo-300x300.png"
  },
  {
    "name": "Louisville Cardinals",
    "slug": "louisville-cardinals",
    "tokens": [
      "louisville",
      "cardinals"
    ],
    "path": "assets/logos/ncaa/Louisville_Cardinals_logo-300x300.png"
  },
  {
    "name": "LSU Tigers",
    "slug": "lsu-tigers",
    "tokens": [
      "lsu",
      "tigers"
    ],
    "path": "assets/logos/ncaa/LSU_Tigers-300x300.png"
  },
  {
    "name": "Marshall Thundering Herd",
    "slug": "marshall-thundering-herd",
    "tokens": [
      "marshall",
      "thundering",
      "herd"
    ],
    "path": "assets/logos/ncaa/Marshall_Thundering_Herd_logo-300x300.png"
  },
  {
    "name": "Maryland Terrapins",
    "slug": "maryland-terrapins",
    "tokens": [
      "maryland",
      "terrapins"
    ],
    "path": "assets/logos/ncaa/Maryland_Terrapins_logo-300x300.png"
  },
  {
    "name": "Memphis Tigers",
    "slug": "memphis-tigers",
    "tokens": [
      "memphis",
      "tigers"
    ],
    "path": "assets/logos/ncaa/Memphis_Tigers_logo-300x300.png"
  },
  {
    "name": "Miami Hurricanes",
    "slug": "miami-hurricanes",
    "tokens": [
      "miami",
      "hurricanes"
    ],
    "path": "assets/logos/ncaa/Miami_Hurricanes_logo-300x300.png"
  },
  {
    "name": "Miami (OH) RedHawks",
    "slug": "miami-oh-redhawks",
    "tokens": [
      "miami",
      "oh",
      "redhawks"
    ],
    "path": "assets/logos/ncaa/Miami_OH_Redhawks_logo-300x300.png"
  },
  {
    "name": "Michigan State Spartans",
    "slug": "michigan-state-spartans",
    "tokens": [
      "michigan",
      "state",
      "spartans"
    ],
    "path": "assets/logos/ncaa/Michigan_State_Spartans_logo-300x300.png"
  },
  {
    "name": "Michigan Wolverines",
    "slug": "michigan-wolverines",
    "tokens": [
      "michigan",
      "wolverines"
    ],
    "path": "assets/logos/ncaa/Michigan_Wolverines_logo-300x300.png"
  },
  {
    "name": "Mid-American Conference",
    "slug": "mid-american-conference",
    "tokens": [
      "mid",
      "american",
      "conference"
    ],
    "path": "assets/logos/ncaa/Mid-American_Conference_logo-300x300.png"
  },
  {
    "name": "Middle Tennessee Blue Raiders",
    "slug": "middle-tennessee-blue-raiders",
    "tokens": [
      "middle",
      "tennessee",
      "blue",
      "raiders"
    ],
    "path": "assets/logos/ncaa/Middle-Tennessee-Blue-Raiders-logo-300x300.png"
  },
  {
    "name": "Minnesota Golden Gophers",
    "slug": "minnesota-golden-gophers",
    "tokens": [
      "minnesota",
      "golden",
      "gophers"
    ],
    "path": "assets/logos/ncaa/Minnesota_Golden_Gophers_logo-300x300.png"
  },
  {
    "name": "Mississippi State Bulldogs",
    "slug": "mississippi-state-bulldogs",
    "tokens": [
      "mississippi",
      "state",
      "bulldogs"
    ],
    "path": "assets/logos/ncaa/Mississippi_State_Bulldogs_logo-300x300.png"
  },
  {
    "name": "Missouri Tigers",
    "slug": "missouri-tigers",
    "tokens": [
      "missouri",
      "tigers"
    ],
    "path": "assets/logos/ncaa/Missouri_Tigers_logo-300x300.png"
  },
  {
    "name": "Mountain West Conference",
    "slug": "mountain-west-conference",
    "tokens": [
      "mountain",
      "west",
      "conference"
    ],
    "path": "assets/logos/ncaa/Mountain_West_Conference_logo-300x300.png"
  },
  {
    "name": "Navy Midshipmen",
    "slug": "navy-midshipmen",
    "tokens": [
      "navy",
      "midshipmen"
    ],
    "path": "assets/logos/ncaa/Navy_Midshipmen_logo-300x300.png"
  },
  {
    "name": "Nebraska Cornhuskers",
    "slug": "nebraska-cornhuskers",
    "tokens": [
      "nebraska",
      "cornhuskers"
    ],
    "path": "assets/logos/ncaa/Nebraska_Cornhuskers_logo-300x300.png"
  },
  {
    "name": "Nevada Wolf Pack",
    "slug": "nevada-wolf-pack",
    "tokens": [
      "nevada",
      "wolf",
      "pack"
    ],
    "path": "assets/logos/ncaa/Nevada_Wolf_Pack_logo-300x300.png"
  },
  {
    "name": "New Mexico Lobos",
    "slug": "new-mexico-lobos",
    "tokens": [
      "new",
      "mexico",
      "lobos"
    ],
    "path": "assets/logos/ncaa/New_Mexico_Lobos_logo-300x300.png"
  },
  {
    "name": "New Mexico State Aggies",
    "slug": "new-mexico-state-aggies",
    "tokens": [
      "new",
      "mexico",
      "state",
      "aggies"
    ],
    "path": "assets/logos/ncaa/New_Mexico_State_Aggies_logo-300x300.png"
  },
  {
    "name": "North Carolina State Wolfpack",
    "slug": "north-carolina-state-wolfpack",
    "tokens": [
      "north",
      "carolina",
      "state",
      "wolfpack"
    ],
    "path": "assets/logos/ncaa/North_Carolina_State_Wolfpack_logo-300x300.png"
  },
  {
    "name": "North Carolina Tar Heels",
    "slug": "north-carolina-tar-heels",
    "tokens": [
      "north",
      "carolina",
      "tar",
      "heels"
    ],
    "path": "assets/logos/ncaa/North_Carolina_Tar_Heels_logo-300x300.png"
  },
  {
    "name": "North Texas Mean Green",
    "slug": "north-texas-mean-green",
    "tokens": [
      "north",
      "texas",
      "mean",
      "green"
    ],
    "path": "assets/logos/ncaa/North_Texas_Mean_Green_logo-300x300.png"
  },
  {
    "name": "Northern Illinois Huskies",
    "slug": "northern-illinois-huskies",
    "tokens": [
      "northern",
      "illinois",
      "huskies"
    ],
    "path": "assets/logos/ncaa/Northern_Illinois_Huskies-300x300.png"
  },
  {
    "name": "Northwestern Wildcats",
    "slug": "northwestern-wildcats",
    "tokens": [
      "northwestern",
      "wildcats"
    ],
    "path": "assets/logos/ncaa/Northwestern_Wildcats_logo-300x300.png"
  },
  {
    "name": "Notre Dame Fighting Irish",
    "slug": "notre-dame-fighting-irish",
    "tokens": [
      "notre",
      "dame",
      "fighting",
      "irish"
    ],
    "path": "assets/logos/ncaa/Notre_Dame_Fighting_Irish_logo-300x300.png"
  },
  {
    "name": "Ohio Bobcats",
    "slug": "ohio-bobcats",
    "tokens": [
      "ohio",
      "bobcats"
    ],
    "path": "assets/logos/ncaa/Ohio_Bobcats_logo-300x300.png"
  },
  {
    "name": "Ohio State Buckeyes",
    "slug": "ohio-state-buckeyes",
    "tokens": [
      "ohio",
      "state",
      "buckeyes"
    ],
    "path": "assets/logos/ncaa/Ohio_State_Buckeyes_logo-300x300.png"
  },
  {
    "name": "Oklahoma Sooners",
    "slug": "oklahoma-sooners",
    "tokens": [
      "oklahoma",
      "sooners"
    ],
    "path": "assets/logos/ncaa/Oklahoma_Sooners_logo-300x300.png"
  },
  {
    "name": "Oklahoma State Cowboys",
    "slug": "oklahoma-state-cowboys",
    "tokens": [
      "oklahoma",
      "state",
      "cowboys"
    ],
    "path": "assets/logos/ncaa/Oklahoma_State_Cowboys_logo-300x300.png"
  },
  {
    "name": "Old Dominion Monarchs",
    "slug": "old-dominion-monarchs",
    "tokens": [
      "old",
      "dominion",
      "monarchs"
    ],
    "path": "assets/logos/ncaa/Old_Dominion_Monarchs_logo-300x300.png"
  },
  {
    "name": "Ole Miss Rebels",
    "slug": "ole-miss-rebels",
    "tokens": [
      "ole",
      "miss",
      "rebels"
    ],
    "path": "assets/logos/ncaa/Ole_Miss_Rebels_logo-300x300.png"
  },
  {
    "name": "Oregon Ducks",
    "slug": "oregon-ducks",
    "tokens": [
      "oregon",
      "ducks"
    ],
    "path": "assets/logos/ncaa/Oregon_Ducks_logo-300x300.png"
  },
  {
    "name": "Oregon State Beavers",
    "slug": "oregon-state-beavers",
    "tokens": [
      "oregon",
      "state",
      "beavers"
    ],
    "path": "assets/logos/ncaa/Oregon_State_Beavers_logo-300x300.png"
  },
  {
    "name": "Pac-12 Conference",
    "slug": "pac-12-conference",
    "tokens": [
      "pac",
      "12",
      "conference"
    ],
    "path": "assets/logos/ncaa/Pac-12_logo-300x300.png"
  },
  {
    "name": "Penn State Nittany Lions",
    "slug": "penn-state-nittany-lions",
    "tokens": [
      "penn",
      "state",
      "nittany",
      "lions"
    ],
    "path": "assets/logos/ncaa/Penn_State_Nittany_Lions_logo-300x300.png"
  },
  {
    "name": "Pittsburgh Panthers",
    "slug": "pittsburgh-panthers",
    "tokens": [
      "pittsburgh",
      "panthers"
    ],
    "path": "assets/logos/ncaa/Pitt_Panthers_logo-300x300.png"
  },
  {
    "name": "Purdue Boilermakers",
    "slug": "purdue-boilermakers",
    "tokens": [
      "purdue",
      "boilermakers"
    ],
    "path": "assets/logos/ncaa/Purdue_Boilermakers_logo-300x300.png"
  },
  {
    "name": "Rice Owls",
    "slug": "rice-owls",
    "tokens": [
      "rice",
      "owls"
    ],
    "path": "assets/logos/ncaa/Rice_Owls_logo-300x300.png"
  },
  {
    "name": "Rutgers Scarlet Knights",
    "slug": "rutgers-scarlet-knights",
    "tokens": [
      "rutgers",
      "scarlet",
      "knights"
    ],
    "path": "assets/logos/ncaa/Rutgers_Scarlet_Knights_logo-300x300.png"
  },
  {
    "name": "Sam Houston Bearkats",
    "slug": "sam-houston-bearkats",
    "tokens": [
      "sam",
      "houston",
      "bearkats"
    ],
    "path": "assets/logos/ncaa/Sam-Houston-State-Bearkats-logo-300x300.png"
  },
  {
    "name": "San Diego State Aztecs",
    "slug": "san-diego-state-aztecs",
    "tokens": [
      "san",
      "diego",
      "state",
      "aztecs"
    ],
    "path": "assets/logos/ncaa/San_Diego_State_Aztecs_logo-300x300.png"
  },
  {
    "name": "San Jose State Spartans",
    "slug": "san-jose-state-spartans",
    "tokens": [
      "san",
      "jose",
      "state",
      "spartans"
    ],
    "path": "assets/logos/ncaa/San_Jose_State_Spartans_logo-300x300.png"
  },
  {
    "name": "SMU Mustangs",
    "slug": "smu-mustangs",
    "tokens": [
      "smu",
      "mustangs"
    ],
    "path": "assets/logos/ncaa/SMU_Mustang_logo-300x300.png"
  },
  {
    "name": "South Alabama Jaguars",
    "slug": "south-alabama-jaguars",
    "tokens": [
      "south",
      "alabama",
      "jaguars"
    ],
    "path": "assets/logos/ncaa/South_Alabama_Jaguars_logo-300x300.png"
  },
  {
    "name": "South Carolina Gamecocks",
    "slug": "south-carolina-gamecocks",
    "tokens": [
      "south",
      "carolina",
      "gamecocks"
    ],
    "path": "assets/logos/ncaa/South_Carolina_Gamecocks_logo-300x300.png"
  },
  {
    "name": "South Florida Bulls",
    "slug": "south-florida-bulls",
    "tokens": [
      "south",
      "florida",
      "bulls"
    ],
    "path": "assets/logos/ncaa/South_Florida_Bulls_logo-300x300.png"
  },
  {
    "name": "SEC",
    "slug": "sec",
    "tokens": [
      "sec"
    ],
    "path": "assets/logos/ncaa/Southeastern_Conference_logo-300x300.png"
  },
  {
    "name": "Southern Miss Golden Eagles",
    "slug": "southern-miss-golden-eagles",
    "tokens": [
      "southern",
      "miss",
      "golden",
      "eagles"
    ],
    "path": "assets/logos/ncaa/Southern_Miss_Golden_Eagles_logo-300x300.png"
  },
  {
    "name": "Stanford Cardinal",
    "slug": "stanford-cardinal",
    "tokens": [
      "stanford",
      "cardinal"
    ],
    "path": "assets/logos/ncaa/Stanford_Cardinal_logo-300x300.png"
  },
  {
    "name": "Sun Belt Conference",
    "slug": "sun-belt-conference",
    "tokens": [
      "sun",
      "belt",
      "conference"
    ],
    "path": "assets/logos/ncaa/Sun_Belt_Conference_2020_logo-300x300.png"
  },
  {
    "name": "Syracuse Orange",
    "slug": "syracuse-orange",
    "tokens": [
      "syracuse",
      "orange"
    ],
    "path": "assets/logos/ncaa/Syracuse_Orange_logo-300x300.png"
  },
  {
    "name": "TCU Horned Frogs",
    "slug": "tcu-horned-frogs",
    "tokens": [
      "tcu",
      "horned",
      "frogs"
    ],
    "path": "assets/logos/ncaa/TCU_Horned_Frogs_logo-300x300.png"
  },
  {
    "name": "Temple Owls",
    "slug": "temple-owls",
    "tokens": [
      "temple",
      "owls"
    ],
    "path": "assets/logos/ncaa/Temple_Owls_logo-300x300.png"
  },
  {
    "name": "Tennessee Volunteers",
    "slug": "tennessee-volunteers",
    "tokens": [
      "tennessee",
      "volunteers"
    ],
    "path": "assets/logos/ncaa/Tennessee_Volunteers_logo-300x300.png"
  },
  {
    "name": "Texas A&M Aggies",
    "slug": "texas-a-m-aggies",
    "tokens": [
      "texas",
      "a",
      "m",
      "aggies"
    ],
    "path": "assets/logos/ncaa/Texas_AM_University_logo-300x300.png"
  },
  {
    "name": "Texas Longhorns",
    "slug": "texas-longhorns",
    "tokens": [
      "texas",
      "longhorns"
    ],
    "path": "assets/logos/ncaa/Texas_Longhorns_logo-300x300.png"
  },
  {
    "name": "Texas State Bobcats",
    "slug": "texas-state-bobcats",
    "tokens": [
      "texas",
      "state",
      "bobcats"
    ],
    "path": "assets/logos/ncaa/Texas_State_Bobcats_logo-300x300.png"
  },
  {
    "name": "Texas Tech Red Raiders",
    "slug": "texas-tech-red-raiders",
    "tokens": [
      "texas",
      "tech",
      "red",
      "raiders"
    ],
    "path": "assets/logos/ncaa/Texas_Tech_Red_Raiders_logo-300x300.png"
  },
  {
    "name": "UTSA Roadrunners",
    "slug": "utsa-roadrunners",
    "tokens": [
      "utsa",
      "roadrunners"
    ],
    "path": "assets/logos/ncaa/Texas-SA-Roadrunners-logo-300x300.png"
  },
  {
    "name": "Toledo Rockets",
    "slug": "toledo-rockets",
    "tokens": [
      "toledo",
      "rockets"
    ],
    "path": "assets/logos/ncaa/Toledo_Rockets_logo-300x300.png"
  },
  {
    "name": "Troy Trojans",
    "slug": "troy-trojans",
    "tokens": [
      "troy",
      "trojans"
    ],
    "path": "assets/logos/ncaa/Troy_Trojans_logo-300x300.png"
  },
  {
    "name": "Tulane Green Wave",
    "slug": "tulane-green-wave",
    "tokens": [
      "tulane",
      "green",
      "wave"
    ],
    "path": "assets/logos/ncaa/Tulane_Green_Wave_logo-300x300.png"
  },
  {
    "name": "Tulsa Golden Hurricane",
    "slug": "tulsa-golden-hurricane",
    "tokens": [
      "tulsa",
      "golden",
      "hurricane"
    ],
    "path": "assets/logos/ncaa/Tulsa_Golden_Hurricane_logo-300x300.png"
  },
  {
    "name": "UCF Knights",
    "slug": "ucf-knights",
    "tokens": [
      "ucf",
      "knights"
    ],
    "path": "assets/logos/ncaa/UCF_Knights_logo-300x300.png"
  },
  {
    "name": "UCLA Bruins",
    "slug": "ucla-bruins",
    "tokens": [
      "ucla",
      "bruins"
    ],
    "path": "assets/logos/ncaa/UCLA_Bruins-300x300.png"
  },
  {
    "name": "UMass Amherst Minutemen",
    "slug": "umass-amherst-minutemen",
    "tokens": [
      "umass",
      "amherst",
      "minutemen"
    ],
    "path": "assets/logos/ncaa/UMass_Amherst_Minutemen_logo-300x300.png"
  },
  {
    "name": "UNLV Rebels",
    "slug": "unlv-rebels",
    "tokens": [
      "unlv",
      "rebels"
    ],
    "path": "assets/logos/ncaa/UNLV_Rebels_logo-300x300.png"
  },
  {
    "name": "USC Trojans",
    "slug": "usc-trojans",
    "tokens": [
      "usc",
      "trojans"
    ],
    "path": "assets/logos/ncaa/USC_Trojans_logo-300x300.png"
  },
  {
    "name": "Utah State Aggies",
    "slug": "utah-state-aggies",
    "tokens": [
      "utah",
      "state",
      "aggies"
    ],
    "path": "assets/logos/ncaa/Utah_State_Aggies_logo-300x300.png"
  },
  {
    "name": "Utah Utes",
    "slug": "utah-utes",
    "tokens": [
      "utah",
      "utes"
    ],
    "path": "assets/logos/ncaa/Utah_Utes_logo-300x300.png"
  },
  {
    "name": "UTEP Miners",
    "slug": "utep-miners",
    "tokens": [
      "utep",
      "miners"
    ],
    "path": "assets/logos/ncaa/UTEP-Miners-logo-300x300.png"
  },
  {
    "name": "Vanderbilt Commodores",
    "slug": "vanderbilt-commodores",
    "tokens": [
      "vanderbilt",
      "commodores"
    ],
    "path": "assets/logos/ncaa/Vanderbilt_Commodores_logo-300x300.png"
  },
  {
    "name": "Virginia Cavaliers",
    "slug": "virginia-cavaliers",
    "tokens": [
      "virginia",
      "cavaliers"
    ],
    "path": "assets/logos/ncaa/Virginia_Cavaliers_logo-300x300.png"
  },
  {
    "name": "Virginia Tech Hokies",
    "slug": "virginia-tech-hokies",
    "tokens": [
      "virginia",
      "tech",
      "hokies"
    ],
    "path": "assets/logos/ncaa/Virginia_Tech_Hokies_logo-300x300.png"
  },
  {
    "name": "Wake Forest Demon Deacons",
    "slug": "wake-forest-demon-deacons",
    "tokens": [
      "wake",
      "forest",
      "demon",
      "deacons"
    ],
    "path": "assets/logos/ncaa/Wake_Forest_Demon_Deacons_logo-300x300.png"
  },
  {
    "name": "Washington Huskies",
    "slug": "washington-huskies",
    "tokens": [
      "washington",
      "huskies"
    ],
    "path": "assets/logos/ncaa/Washington_Huskies_logo-300x300.png"
  },
  {
    "name": "Washington State Cougars",
    "slug": "washington-state-cougars",
    "tokens": [
      "washington",
      "state",
      "cougars"
    ],
    "path": "assets/logos/ncaa/Washington_State_Cougars_logo-300x300.png"
  },
  {
    "name": "West Virginia Mountaineers",
    "slug": "west-virginia-mountaineers",
    "tokens": [
      "west",
      "virginia",
      "mountaineers"
    ],
    "path": "assets/logos/ncaa/West_Virginia_Mountaineers_logo-300x300.png"
  },
  {
    "name": "Western Kentucky Hilltoppers",
    "slug": "western-kentucky-hilltoppers",
    "tokens": [
      "western",
      "kentucky",
      "hilltoppers"
    ],
    "path": "assets/logos/ncaa/Western_Kentucky_Hilltoppers_logo-300x300.png"
  },
  {
    "name": "Western Michigan Broncos",
    "slug": "western-michigan-broncos",
    "tokens": [
      "western",
      "michigan",
      "broncos"
    ],
    "path": "assets/logos/ncaa/Western_Michigan_Broncos_logo-300x300.png"
  },
  {
    "name": "Wisconsin Badgers",
    "slug": "wisconsin-badgers",
    "tokens": [
      "wisconsin",
      "badgers"
    ],
    "path": "assets/logos/ncaa/Wisconsin_Badgers_logo-300x300.png"
  },
  {
    "name": "Wyoming Cowboys",
    "slug": "wyoming-cowboys",
    "tokens": [
      "wyoming",
      "cowboys"
    ],
    "path": "assets/logos/ncaa/Wyoming_Cowboys_logo-300x300.png"
  }
] as const;

export const NCAA_LOGO_INDEX: Readonly<Record<string, LogoEntry>> = Object.fromEntries(NCAA_LOGOS.map(entry => [entry.slug, entry]));

export const NCAA_LOGO_ALIASES: Readonly<Record<string, string>> = {
  "alabama-birmingham-blazers": "uab-blazers",
  "brigham-young-cougars": "byu-cougars",
  "louisiana-state-tigers": "lsu-tigers",
  "southern-methodist-mustangs": "smu-mustangs",
  "texas-christian-horned-frogs": "tcu-horned-frogs",
  "central-florida-knights": "ucf-knights",
  "fau-owls": "florida-atlantic-owls",
  "florida-international-panthers": "fiu-panthers",
  "texas-san-antonio-roadrunners": "utsa-roadrunners",
  "texas-el-paso-miners": "utep-miners",
  "southern-california-trojans": "usc-trojans",
  "california-los-angeles-bruins": "ucla-bruins",
  "nevada-las-vegas-rebels": "unlv-rebels",
  "miami-ohio-redhawks": "miami-oh-redhawks",
  "pitt-panthers": "pittsburgh-panthers",
  "nc-state-wolfpack": "north-carolina-state-wolfpack",
  "vt-hokies": "virginia-tech-hokies",
  "mississippi-rebels": "ole-miss-rebels",
  "ull-ragin-cajuns": "louisiana-ragin-cajuns",
  "louisiana-monroe-warhawks": "ulm-warhawks",
  "texas-am-aggies": "texas-a-m-aggies",
  "texas-a-m-aggies": "texas-a-m-aggies",
  "fbs-independents": "division-i-fbs-independents",
  "mtsu-blue-raiders": "middle-tennessee-blue-raiders",
  "jmu-dukes": "james-madison-dukes",
  "nd-fighting-irish": "notre-dame-fighting-irish",
  "ou-sooners": "oklahoma-sooners",
  "okstate-cowboys": "oklahoma-state-cowboys",
  "ku-jayhawks": "kansas-jayhawks",
  "ksu-wildcats": "kansas-state-wildcats",
  "mizzou-tigers": "missouri-tigers",
  "fsu-seminoles": "florida-state-seminoles",
  "gt-yellow-jackets": "georgia-tech-yellow-jackets",
  "wvu-mountaineers": "west-virginia-mountaineers",
  "wsu-cougars": "washington-state-cougars",
  "uw-huskies": "washington-huskies",
  "asu-sun-devils": "arizona-state-sun-devils",
  "ua-wildcats": "arizona-wildcats",
  "notre-dame": "notre-dame-fighting-irish",
  "uab-blazers": "uab-blazers",
  "utsa-roadrunners": "utsa-roadrunners",
  "utep-miners": "utep-miners",
  "fiu-panthers": "fiu-panthers",
  "ole-miss-rebels": "ole-miss-rebels",
  "byu-cougars": "byu-cougars",
  "lsu-tigers": "lsu-tigers",
  "smu-mustangs": "smu-mustangs",
  "tcu-horned-frogs": "tcu-horned-frogs",
  "ucf-knights": "ucf-knights",
  "usc-trojans": "usc-trojans",
  "ucla-bruins": "ucla-bruins",
  "unlv-rebels": "unlv-rebels",
  "purdue-boilermakers": "purdue-boilermakers"
};
