name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Install pnpm once before setting up Node.js cache
      - name: Setup pnpm (standalone)
        uses: pnpm/action-setup@v4
        with:
          standalone: true
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Verify pnpm on PATH
        run: |
          pnpm -v
          which pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Typecheck
        run: pnpm run --if-present typecheck

      - name: Lint
        run: pnpm run --if-present lint

      - name: Test
        env:
          CI: "1"
        run: pnpm run --if-present test

      - name: Build
        run: |
          pnpm run clean
          pnpm run prepare:logos
          pnpm run build:ts
          pnpm run build:pages
          python3 scripts/build_site.py || true
          pnpm run build:sitemap
