name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Ensure pnpm
        uses: ./.github/actions/ensure-pnpm
        with:
          version: 9

      - name: Tooling diagnostics
        shell: bash
        run: |
          set -x
          node -v
          which node
          pnpm -v
          which pnpm
          printenv | sort | sed -n '1,120p'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck --if-present

      - name: Lint
        run: pnpm run lint --if-present

      - name: Test
        env:
          CI: "1"
        run: pnpm run test --if-present

      - name: Build
        run: pnpm run build --if-present
