name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # NCAAM Worker base
      NCAAM_BASE: https://ncaam.hicksrch.workers.dev/ncaam
      # Optional: diag endpoint if a script uses it
      NCAAM_DIAG: https://ncaam.hicksrch.workers.dev/diag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Ensure pnpm
        uses: ./.github/actions/ensure-pnpm
        with:
          version: 9

      - name: Tooling diagnostics
        shell: bash
        run: |
          set -x
          node -v
          which node
          pnpm -v
          which pnpm
          printenv | sort | sed -n '1,120p'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Set Vite base for GitHub Pages
        shell: bash
        run: |
          REPO="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [[ "$REPO" == "${OWNER}.github.io" ]]; then
            echo "VITE_BASE=/" >> "$GITHUB_ENV"
            echo "SITE_BASE=https://${OWNER}.github.io" >> "$GITHUB_ENV"
          else
            echo "VITE_BASE=/${REPO}/" >> "$GITHUB_ENV"
            echo "SITE_BASE=https://${OWNER}.github.io/${REPO}" >> "$GITHUB_ENV"
          fi

      - name: Typecheck (if present)
        run: pnpm run typecheck --if-present

      - name: Lint (if present)
        run: pnpm run lint --if-present

      - name: Build site data (if present)
        env:
          NCAAM_BASE: https://ncaam.hicksrch.workers.dev/ncaam
          BDL_PROXY_BASE: https://ncaam.hicksrch.workers.dev/ncaam
        run: pnpm run build:data --if-present

      - name: Build site (if present)
        env:
          VITE_BASE: ${{ env.VITE_BASE }}
        run: pnpm run build --if-present

      - name: Build sitemap/robots (if script present)
        run: |
          if [ -f scripts/build_sitemap.mjs ]; then
            node scripts/build_sitemap.mjs
          else
            echo "No sitemap script; skipping."
          fi

      - name: Select Pages artifact directory
        id: pickdir
        shell: bash
        run: |
          if [ -d dist ]; then
            echo "BUILD_DIR=dist" >> "$GITHUB_ENV"
            echo "dir=dist" >> "$GITHUB_OUTPUT"
          elif [ -d public ]; then
            echo "BUILD_DIR=public" >> "$GITHUB_ENV"
            echo "dir=public" >> "$GITHUB_OUTPUT"
          else
            mkdir -p public
            if [ -f index.html ]; then
              cp index.html public/index.html
            else
              echo '<!doctype html><meta charset="utf-8"><title>NCAA Hub</title><div id="app">Build produced no dist/public. Placeholder deployed.</div>' > public/index.html
            fi
            echo "BUILD_DIR=public" >> "$GITHUB_ENV"
            echo "dir=public" >> "$GITHUB_OUTPUT"
          fi
          echo "Using ${{ steps.pickdir.outputs.dir }} as artifact path."

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
